#!/usr/bin/env bash
# Installs, configures, and starts the server

#!/usr/bin/env bash
#  A Script that configures a new Ubuntu machine to Perform a 301-redirection

# Upadating Packages before Installations
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a 301 Redirection
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/besthor permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restarting Nginx service
sudo service nginx restart

#apt-get update
#apt-get -y install nginx
#sudo ufw allow 'Nginx HTTP'
#mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
#echo 'Hello World!' > /var/www/html/index.html
#SERVER_CONFIG=\
#"server {
#	listen 80 default_server;
#	listen [::]:80 default_server;
#	root /var/www/html;
#	index index.html index.htm index.nginx-debian.html;
#	server_name _;
#	location / {
#		try_files \$uri \$uri/ =404;
#	}
#	if (\$request_filename ~ redirect_me){
#		rewrite ^ https://sketchfab.com/bluepeno/models permanent;
#	}
#}"

#bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

#if [ "$(pgrep -c nginx)" -le 0 ]; then
#	service nginx start
#else
#	service nginx restart
#fi
