#!/usr/bin/env bash
# Installs, configures, and starts the server

# Upadating Packages before Installations
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a 301 Redirection
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/" /etc/nginx/sites-available/default

# Restarting Nginx service
if [ "$(pgrep -c nginx)" -le 0 ]; then
	sudo service nginx start
else
	sudo service nginx restart
fi

#sudo chmod -R 755 /var/www
#SERVER_CONFIG=\
#"server {
#	listen 80 default_server;
#	listen [::]:80 default_server;
#	root /var/www/html;
#	index index.html index.htm index.nginx-debian.html;
#	server_name _;
#	location / {
#		try_files \$uri \$uri/ =404;
#	}
#	if (\$request_filename ~ redirect_me){
#		rewrite ^ https://link permanent;
#	}
#}"

#bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

#if [ "$(pgrep -c nginx)" -le 0 ]; then
#	service nginx start
#else
#	service nginx restart
#fi
